context:
  version: "1.16.0"

package:
  name: aardvark-dns
  version: ${{ version }}

source:
  url: https://github.com/containers/aardvark-dns/archive/refs/tags/v${{ version }}.tar.gz
  # run “curl -sL $url | sha256sum” to update
  sha256: 6c84a3371087d6af95407b0d3de26cdc1e720ae8cd983a9bdaec8883e2216959

build:
  skip:
    - win
  number: 0
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - cargo install --locked --root="${PREFIX}" --path .

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - make

tests:
  - script:
      - aardvark-dns --version
      - aardvark-dns --help | head -n 5

about:
  homepage: https://github.com/containers/aardvark-dns
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: "Authoritative DNS server for A/AAAA container records"

extra:
  recipe-maintainers:
    - 2themaxx
